set(CTEST_PROJECT_NAME "StuPro")
set(CTEST_NIGHTLY_START_TIME "00:00:00 UTC")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "129.217.165.251")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=StuPro")
set(CTEST_DROP_SITE_CDASH TRUE)
